### ISSUE TITLE
'elementType' should be replaced by 'class' in the config.php docs

### ISSUE THREAD

**Issue by pierrestoffe** [riasvdv/craft-notifications#20]
Hi,

Just noticed that the docs in the config.php file reference a wrong key. 'elementType' should be replaced by 'class' if I'm not mistaken.

https://github.com/Rias500/craft-notifications/blob/0c3231c39e699c42debd56885468933586de4e4a/src/config.php#L9

**Comment by Saboteur777** [comment]
You are right, else `Undefined index: class` error is thrown.
